name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  common:
    path: ../../packages/common
  dart_frog: ^1.2.3
  dart_frog_auth: ^1.2.1
  dart_jsonwebtoken: ^3.2.0
  dotenv: ^4.2.0
  drift: ^2.14.1
  http: ^1.5.0
  shelf_cors_headers: ^0.1.5
  sqlite3: ^2.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.7.0
  drift_dev: ^2.14.1
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
