name: common
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  dart_mappable: ^4.6.0
  luthor: ^0.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.7.0
  dart_mappable_builder: ^4.6.0
  lints: ^6.0.0
  test: ^1.25.6
